services:
  entrypoint:
    image: caddy:2.8.4-alpine
    ports:
      - "443:443"
    command: caddy run --watch --adapter caddyfile --config /etc/caddy/Caddyfile
    volumes:
      - ./src/development.Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data # For storing Caddy's root CA certificate in a persistent manner
    depends_on:
      - app1_client
    networks:
      stxtauth:
        # We need to hardcode a static IP here to be referenced by other containers as a DNS server
        # to be able to internally resolve the same hostnames as externally (e.g. https://login.stxt-auth.localhost)
        ipv4_address: "192.168.45.251"
  app1_client:
    networks:
      - stxtauth
    build: src/app1/client
    volumes:
      - ./src/app1/client/src:/app/src
      - ./src/app1/client/public:/app/public
      - ./src/app1/client/package.json:/app/package.json
      - ./src/app1/client/package-lock.json:/app/package-lock.json
      - ./src/shared:/app/shared
      - ./src/app1/client/node_modules/shared:/app/node_modules/shared
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
#  app1_server:
#    networks:
#      - proxy
#    build: ./app1/server
#    volumes:
#      - ./app1/server/src:/app/src
#      - ./app1/server/package.json:/app/package.json
#      - ./app1/server/package-lock.json:/app/package-lock.json
#      - /app/node_modules
#    ports:
#      - "3001:3000"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.app1-server.rule=Host(`api.app1.local`)"
#      - "traefik.http.routers.app1-server.entrypoints=web"
#      - "traefik.http.services.app1-server.loadbalancer.server.port=3000"
#    environment:
#      - NODE_ENV=development
  app2_client:
    networks:
      - stxtauth
    build: src/app2/client
    volumes:
      - ./src/app2/client/src:/app/src
      - ./src/app2/client/public:/app/public
      - ./src/app2/client/package.json:/app/package.json
      - ./src/app2/client/package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
  login_client:
    networks:
      - stxtauth
    build: src/login/client
    volumes:
      - ./src/login/client/src:/app/src
      - ./src/login/client/public:/app/public
      - ./src/login/client/package.json:/app/package.json
      - ./src/login/client/package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000

networks:
  stxtauth:
    name: stxt-auth-network-default
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.45.0/24"