version: '3.8'

services:
  traefik:
    networks:
      - proxy
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    labels:
      - "traefik.http.middlewares.cors.headers.accessControlAllowOrigin=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,OPTIONS,PUT,POST,DELETE"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      #- "traefik.http.middlewares.cors.headers.addVaryHeader=true"
  app1_client:
    networks:
      - proxy
    build: ./app1/client
    volumes:
      - ./app1/client/src:/app/src
      - ./app1/client/public:/app/public
      - ./app1/client/package.json:/app/package.json
      - ./app1/client/package-lock.json:/app/package-lock.json
      - ./shared:/app/shared
      - /app/node_modules
      - /app/node_modules/shared:/app/node_modules/shared
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000 # The mapped port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`app1.local`)"
      - "traefik.http.routers.app1.entrypoints=web"
      - "traefik.http.services.app1.loadbalancer.server.port=3000"
      #- "traefik.http.routers.app1.middlewares=cors@docker"
  app1_server:
    networks:
      - proxy
    build: ./app1/server
    volumes:
      - ./app1/server/src:/app/src
      - ./app1/server/package.json:/app/package.json
      - ./app1/server/package-lock.json:/app/package-lock.json
      - /app/node_modules
    ports:
      - "3001:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1-server.rule=Host(`api.app1.local`)"
      - "traefik.http.routers.app1-server.entrypoints=web"
      - "traefik.http.services.app1-server.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=development
  app2_client:
    networks:
      - proxy
    build: ./app2/client
    volumes:
      - ./app2/client/src:/app/src
      - ./app2/client/public:/app/public
      - ./app2/client/package.json:/app/package.json
      - ./app2/client/package-lock.json:/app/package-lock.json
      - /app/node_modules
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000 # The mapped port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app2.local`)"
      - "traefik.http.routers.app2.entrypoints=web"
      - "traefik.http.services.app2.loadbalancer.server.port=3000"
      #- "traefik.http.routers.app2.middlewares=cors@docker"
  app2_server:
    networks:
      - proxy
    build: ./app2/server
    volumes:
      - ./app2/server/src:/app/src
      - ./app2/server/package.json:/app/package.json
      - ./app2/server/package-lock.json:/app/package-lock.json
    ports:
      - "3004:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2-server.rule=Host(`api.app2.local`)"
      - "traefik.http.routers.app2-server.entrypoints=web"
      - "traefik.http.services.app2-server.loadbalancer.server.port=3000"
      #- "traefik.http.routers.app2-server.middlewares=cors@docker"
    environment:
      - NODE_ENV=development
  login_client:
    networks:
      - proxy
    build: ./login/client
    volumes:
      - ./login/client/src:/app/src
      - ./login/client/public:/app/public
      - ./login/client/package.json:/app/package.json
      - ./login/client/package-lock.json:/app/package-lock.json
      - /app/node_modules
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000 # The mapped port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.login.rule=Host(`login.local`)"
      - "traefik.http.routers.login.entrypoints=web"
      - "traefik.http.services.login.loadbalancer.server.port=3000"
      #- "traefik.http.routers.login.middlewares=cors@docker"
  login_server:
    networks:
      - proxy
    build: ./login/server
    volumes:
      - ./login/server/src:/app/src
      - ./login/server/package.json:/app/package.json
      - ./login/server/package-lock.json:/app/package-lock.json
    ports:
      - "3005:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.login-server.rule=Host(`api.login.local`)"
      - "traefik.http.routers.login-server.entrypoints=web"
      - "traefik.http.services.login-server.loadbalancer.server.port=3000"
      #- "traefik.http.routers.login-server.middlewares=cors@docker"
    environment:
      - NODE_ENV=development

networks:
  proxy:
    external: true
  default:
    external:
      name: loginapp-network