version: '3.8'

services:
  app1:
    build: .
    ports:
      - "3000:3000"
    environment:
      - KEYCLOAK_URL=http://keycloak-server:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myapp
      - SESSION_SECRET=secret1
      - PORT=3000

  app2:
    build: .
    ports:
      - "3001:3000"
    environment:
      - KEYCLOAK_URL=http://keycloak-server:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myapp
      - SESSION_SECRET=secret2
      - PORT=3000
