version: '3.8'

services:
  app1_client:
    build: ./app1/client
    ports:
      - "3001:80"
    depends_on:
      - app1_server

  app1_server:
    build: ./app1/server
    ports:
      - "3002:3000"

#  app2_client:
#    build: ./app2/client
#    ports:
#      - "3003:80"
#    depends_on:
#      - app2_server
#
#  app2_server:
#    build: ./app2/server
#    ports:
#      - "3004:3000"

  login_client:
    build: ./login/client
    ports:
      - "3005:80"
#    depends_on:
#      - login_server

#  login_server:
#    build: ./login/server
#    ports:
#      - "3006:3000"

#  keycloak:
#    image: jboss/keycloak
#    environment:
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#    ports:
#      - "8080:8080"

networks:
  default:
    external:
      name: loginapp-network