api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

log:
  filePath: "log-file.log"
  format: json
  level: DEBUG

http:
  middlewares:
    cors:
      headers:
        accessControlAllowOrigin: "*"
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        addVaryHeader: true
providers:
  docker:
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

