services:
  setup:
    image: caddy:2.8.4-alpine
    ports:
      - "127.0.0.1:2019:2019" # Caddy Admin API - only necessary for initially trusting its CA certificate.
    command: caddy run --watch --adapter caddyfile --config /etc/caddy/Caddyfile
    volumes:
      - ./setup/setup.Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data # Keep this in sync with the main docker-compose.yml!